In [35]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [36]:
## LOAD ANN TRAINER MODEL, SCALER PICKEL FILE

model=load_model('model.h5')

##LOAD ENCODER AND SCALER

with open('onehot_encoder.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encode_gender.pkl','rb') as file:
    label_encode_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler= pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [37]:
## EXAMPLE INPUT DATA
input_data ={
    'CreditScore' : 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts': 2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [38]:
## ONE HOT ENCODE 'Geography'

geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/Users/samarthmehra/Downloads/CODING PROJECTS GEN AI/nevn/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [39]:
input_df=pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [43]:
#Encode Categorical values
input_df['Gender']=label_encode_gender.fit_transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       0  ...          1               1            50000

[1 rows x 10 columns]

In [46]:
##Concatination

input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)

In [47]:
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       0  ...                0.0              0.0

[1 rows x 12 columns]

In [49]:
##SCALING THE INPUT DATA

input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.47154541, -1.09997489,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [51]:
##PREDICTION
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

array([[0.07878038]], dtype=float32)

In [52]:
prediction_prob=prediction[0][0]

In [53]:
prediction_prob

np.float32(0.078780375)